export const SITE = {
  website: "https://jamesmensch.com/",
  author: "James Mensch",
  profile: "https://jamesmensch.com/",
  desc: "I build developer tools and the kind of infrastructure most people don't notice when it's working. Most of my writing is about Claude Code, agent workflows, and a homelab running on a small NUC. I'm based in Austin with three dogs.",
  title: "James Mensch",
  ogImage: "og.png",
  lightAndDarkMode: false,
  postPerIndex: 4,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/Chicago",
} as const;
