export const SITE = {
  website: "https://jamesmensch.com/",
  author: "James Mensch",
  profile: "https://jamesmensch.com/",
  desc: "James Mensch, building products that make the world a better place.",
  title: "James Mensch",
  ogImage: "og.png",
  lightAndDarkMode: false,
  postPerIndex: 4,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/Chicago",
} as const;
